from .categoria import CategoriaSerializer
from .entidade import EntidadeSerializer
from .permissao import PermissaoSerializer
from .modelo import ModeloSerializer
from .sala import SalaSerializer
from .usuario import UsuarioSerializer
from .dispositivo import DispositivoSerializer
from .usuario_permissao import UsuarioPermissaoSerializer
from .ticket import TicketSerializer
from .manutencao import ManutencaoSerializer
from .historico_dispositivo import HistoricoDispositivoSerializer
from .historico_ticket import HistoricoTicketSerializer
