# Generated by Django 6.0.5 on 2026-10-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-criado_em', '-id'], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AddField(
            model_name='ticket',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tipo_problema',
            field=models.CharField(choices=[('hardware', 'Hardware'), ('software', 'Software'), ('rede', 'Rede'), ('periferico', 'Periférico'), ('outro', 'Outro')], default='outro', max_length=20),
        ),
    ]
