from .categoria import Categoria
from .entidade import Entidade
from .permissao import Permissao
from .modelo import Modelo
from .sala import Sala
from .usuario import Usuario
from .dispositivo import Dispositivo
from .usuario_permissao import UsuarioPermissao
from .ticket import Ticket
